### ISSUE TITLE
how to open the application

### ISSUE THREAD

**Issue by yashwanth938** [ShaanCoding/makeread.me#13]
can you tell me hoe to run the application, i follow the instructions i clone the repo and opened the html file but blank white page opened that should i have to install node moduled ??

**Comment by ShaanCoding** [comment]
Hi thanks for the PR, at the moment I'm doing a large refactor of this project with @dukeofsoftware in the `develop` and `main` branches respectively. These have not been updated, but `develop` currently uses pnpm instead of yarn and is not stable as of date.

To run / try out the one currently on readme.shaankhan.dev, please have a look at the `readme-generator-2020` branch

**Comment by ShaanCoding** [comment]
MVP of Major refactor has been done, documentation has been updated to support installation steps. Closing this issue
