### ISSUE TITLE
IP Address Tracker

### ISSUE THREAD

**Issue by mianni1** [ShaanCoding/makeread.me#29]
## Feature Details

IP address tracker

## Expected Functionality

Reverse Proxy acting as IP logger

## Design

Purely backend

**Comment by ShaanCoding** [comment]
Hi thanks for raising a suggestion in this project.

However, I'd like to clarify that privacy is a core value of this open-source project. Due to this, I've chosen to utilize Plausible for analytics which offers high-level anonymized user statistics over Google Analytics, helping us prioritize our feature developments without compromising on user privacy. 

Regarding your suggestion of incorporating an IP tracker, it's a proposition that goes against our foundational principles. As such, we will not be considering this feature, now or in the future.

**Comment by thonk3** [comment]
I sec-coned this, please reopen
