### ISSUE TITLE
How can we start helping?

### ISSUE THREAD

**Issue by MathPow** [ShaanCoding/makeread.me#43]
I made a small frontend fix locally and when I tried make a pull request or anything really, I didn't have permission. How can we start collaborating on this open-source project? I found a section in the README about collaborating, so I thought it was something I could do straight away.

**Comment by ShaanCoding** [comment]
Hey, firstly thanks for using this repository. I appreciate you taking time out of your day to use this app, and even contribute! 

I've had a review of the permissions and have had previous contributors on this project who didn't have contributor access and they were all able to raise pull-requests & collaborate.

I think the most likely issue here is, that you've **cloned** the repository instead of **forking** the repository, meaning the source still points to `ShaanCoding/makeread.me` instead of something like `MathPow/makeread.me`. By forking this repo and creating a clone, you should be able to raise a pull-request, with you merging your branch from your source repo to mine, without having read-write access to this specific project.

I'd have a look at the following article and see if it helps solve your problems, if it's something different feel free to reach out here. https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project

**Comment by MathPow** [comment]
Yes, I cloned the repository. I will try forking it. Thanks a lot!
